/* eslint-disable react/no-unescaped-entities */
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Script from "next/script";

const exo = Exo({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Clothings Bee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>Clothings Bee</title>
        <meta name="description" content="Generated by create next app" />

        {/* Facebook Pixel Code */}
        <Script id="fb-pixel" strategy="afterInteractive">
          {`
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '640186175199186');
            fbq('track', 'PageView');
          `}
        </Script>
      </head>
      <body className={exo.className}>
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=640186175199186&ev=PageView&noscript=1"
          />
        </noscript>
        {/* <Navbar />
        {children} */}

        <div>
          <div className="bg-gradient-to-r from-slate-200 to-gray-200 dark:from-gray-800 dark:to-gray-900 text-black dark:text-white">
            <div className="flex items-center justify-center min-h-screen px-2">
              <div className="text-center">
                <h1 className="text-9xl font-bold">404</h1>
                <p className="text-2xl font-medium mt-4">
                  Oops! Page not found
                </p>
                <p className="mt-4 mb-8">
                  The page you're looking for doesn't exist
                </p>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
